# Generated by Django 4.2.5 on 2025-02-03 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('todos', '0001_initial'), ('todos', '0002_alter_todo_options_alter_todo_date_completed_and_more'), ('todos', '0003_alter_todo_done_alter_todo_name_alter_todo_user'), ('todos', '0004_alter_todo_date_completed')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Todo name')),
                ('done', models.BooleanField(default=False, verbose_name='Todo Done')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date of Creation')),
                ('date_completed', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date of Completion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'To-Do',
                'verbose_name_plural': 'To-Dos',
            },
        ),
    ]
